version: "2"

services:


  sse-service:
    build: ./
    image: serservice

  engine:
    image: qlikcore/engine:12.387.0
    
    command: |
      - -S AcceptEULA=yes 
      - -S DocumentDirectory=/apps
      - -S EnableGrpcCustomConnectors=1
      - -S GrpcConnectorPlugins="testconnector,sse-service:50053"
      - -S ScriptLogVerbosity=5 
      - -S SessionLogVerbosity=5
      - -S ScriptLogVerbosity=5 
      - -S SessionLogVerbosity=5

    volumes:
      - ./assets/apps:/apps
      
    ports:
      - 9077:9076

    depends_on:
      - sse-service