version: "2"

services:

  dotnet-grpc-service:
    build: ../../src/
    image: dotnetservice

  engine:
    image: qlikcore/engine:12.387.0
    
    command: |
      - -S AcceptEULA=yes 
      - -S DocumentDirectory=/apps
      - -S EnableGrpcCustomConnectors=1
      - -S GrpcConnectorPlugins="testconnector,dotnet-grpc-service:50053"
      - -S ScriptLogVerbosity=5 
      - -S SessionLogVerbosity=5
      - -S ScriptLogVerbosity=5 
      - -S SessionLogVerbosity=5

    volumes:
      - ./assets/apps:/apps
      
    ports:
      - 9077:9076

    depends_on:
      - dotnet-grpc-service